version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
    ports:
      - 1433:1433

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2081:2081

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - 9092:9092

  kafka-ui:
    image: provectuslabs/kafka-ui
    network_mode: "host"
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
    depends_on: 
      - kafka
      - zookeeper
